tables:
  DIM:
    accounts: public.maka_dwh_dim_accounts_hist
    cards: public.maka_dwh_dim_cards_hist
    clients: public.maka_dwh_dim_clients_hist
    terminals: public.maka_dwh_dim_terminals_hist

  FACT:
    blacklist: public.maka_dwh_fact_passport_blacklist
    transactions: public.maka_dwh_fact_transactions

  STG:
    accounts: public.maka_stg_accounts
    blacklist: public.maka_stg_blacklist
    cards: public.maka_stg_cards
    clients: public.maka_stg_clients
    terminals: public.maka_stg_terminals
    transactions: public.maka_stg_transactions

  REP:
    fraud: public.maka_rep_fraud

fact_mapping:
  blacklist:
    passport: passport_num
    date: entry_dt
  transactions:
    transaction_id: trans_id
    transaction_date: trans_date
    amount: amt
    card_num: card_num
    oper_type: oper_type
    oper_result: oper_result
    terminal: terminal

scd2:
  accounts:
    mapping:
      account: account_num
      valid_to: valid_to
      client: client
    stg_pk: account
    dim_pk: account_num
    date_col: update_dt
  cards:
    mapping:
      card_num: cards_num
      account: account_num
    stg_pk: card_num
    dim_pk: cards_num
    date_col: update_dt
  clients:
    mapping:
      client_id: client_id
      last_name: last_name
      first_name: first_name
      patronymic: patronymic
      date_of_birth: date_of_birth
      passport_num: passport_num
      passport_valid_to: passport_valid_to
      phone: phone
    stg_pk: client_id
    dim_pk: client_id
    date_col: update_dt
  terminals:
    mapping:
      terminal_id: terminal_id
      terminal_type: terminal_type
      terminal_city: terminal_city
      terminal_address: terminal_address
    stg_pk: terminal_id
    dim_pk: terminal_id
    date_col: date
